<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Update="ResourcesMessagesExceptions.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>ResourcesMessagesExceptions.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="ResourcesMessagesExceptions.pt-BR.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>ResourcesMessagesExceptions.pt-BR.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="ResourcesMessagesExceptions.fr.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>ResourcesMessagesExceptions.fr.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="ResourcesMessagesExceptions.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>ResourcesMessagesExceptions.resx</DependentUpon>
      </Compile>
      <Compile Update="ResourcesMessagesExceptions.pt-BR.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>ResourcesMessagesExceptions.pt-BR.resx</DependentUpon>
      </Compile>
      <Compile Update="ResourcesMessagesExceptions.fr.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>ResourcesMessagesExceptions.fr.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
